// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Webapp_Dieselskandal.Data;

#nullable disable

namespace Webapp_Dieselskandal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Webapp_Dieselskandal.Models.Auftrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AktualisiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AndereKanzleiBeauftragt")
                        .HasColumnType("boolean");

                    b.Property<int>("Baujahr")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fahrgestellnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FahrzeugInBesitz")
                        .HasColumnType("boolean");

                    b.Property<string>("Haendler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hersteller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Kaufdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Kaufpreis")
                        .HasColumnType("numeric");

                    b.Property<string>("Kennzeichen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("KlageDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("KlageEingereicht")
                        .HasColumnType("boolean");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Waehrung")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Auftraege");
                });

            modelBuilder.Entity("Webapp_Dieselskandal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Webapp_Dieselskandal.Models.Auftrag", b =>
                {
                    b.HasOne("Webapp_Dieselskandal.Models.User", "User")
                        .WithMany("Auftraege")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webapp_Dieselskandal.Models.User", b =>
                {
                    b.Navigation("Auftraege");
                });
#pragma warning restore 612, 618
        }
    }
}
